FROM php:8.4-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        curl \
        libpq-dev \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        libicu-dev \
        unzip \
    && docker-php-ext-install \
        zip \
        intl \
        opcache \
        pdo pdo_pgsql

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY app/ /var/www/symfony
WORKDIR /var/www/symfony

COPY --link \
    --from=ghcr.io/symfony-cli/symfony-cli:latest \
    /usr/local/bin/symfony /usr/local/bin/symfony