<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260610195026 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE device (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, serial_number VARCHAR(16) NOT NULL, model VARCHAR(255) NOT NULL, customer_name VARCHAR(30) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE technician (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(30) NOT NULL, last_name VARCHAR(50) NOT NULL, email VARCHAR(100) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, priority VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, assigned_technician_id INT DEFAULT NULL, device_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97A0ADA35CF77DD3 ON ticket (assigned_technician_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA394A4C7D4 ON ticket (device_id)');
        $this->addSql('CREATE TABLE ticket_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, old_status VARCHAR(255) NOT NULL, new_status VARCHAR(255) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ticket_id INT DEFAULT NULL, changed_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B762919700047D2 ON ticket_history (ticket_id)');
        $this->addSql('CREATE INDEX IDX_2B762919828AD0A0 ON ticket_history (changed_by_id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA35CF77DD3 FOREIGN KEY (assigned_technician_id) REFERENCES technician (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA394A4C7D4 FOREIGN KEY (device_id) REFERENCES device (id)');
        $this->addSql('ALTER TABLE ticket_history ADD CONSTRAINT FK_2B762919700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id)');
        $this->addSql('ALTER TABLE ticket_history ADD CONSTRAINT FK_2B762919828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES technician (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA35CF77DD3');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA394A4C7D4');
        $this->addSql('ALTER TABLE ticket_history DROP CONSTRAINT FK_2B762919700047D2');
        $this->addSql('ALTER TABLE ticket_history DROP CONSTRAINT FK_2B762919828AD0A0');
        $this->addSql('DROP TABLE device');
        $this->addSql('DROP TABLE technician');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE ticket_history');
    }
}
